general {
    hide_cursor = true
}

background {
    monitor =
    color = rgba(10, 10, 10, 1.0)
}

input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2

    outer_color = rgba(200, 200, 200, 1.0)
    inner_color = rgba(30, 30, 30, 1.0)
    font_color = rgba(240, 240, 240, 1.0)

    placeholder_text = <i>Password...</i>
    fail_text = <i>Authentication failed ($ATTEMPTS)</i>

    position = 0, 0
    halign = center
    valign = center
}
